<span class="dropdown">
    <button id="currencyDropdown" class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span id="currCurrencyCode">Price (USD)</span><span class="caret"></span>
    </button>
    <ul class="dropdown-menu" id="currencyList">
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AED">AED</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AFN">AFN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ALL">ALL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AMD">AMD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ANG">ANG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AOA">AOA</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ARS">ARS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AUD">AUD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AWG">AWG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="AZN">AZN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BAM">BAM</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BBD">BBD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BDT">BDT</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BGN">BGN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BHD">BHD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BIF">BIF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BMD">BMD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BND">BND</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BOB">BOB</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BRL">BRL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BSD">BSD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BTC">BTC</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BTN">BTN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BWP">BWP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BYN">BYN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="BZD">BZD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CAD">CAD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CDF">CDF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CHF">CHF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CLF">CLF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CLP">CLP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CNH">CNH</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CNY">CNY</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="COP">COP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CRC">CRC</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CUC">CUC</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CUP">CUP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CVE">CVE</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="CZK">CZK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="DJF">DJF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="DKK">DKK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="DOP">DOP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="DZD">DZD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="EGP">EGP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ERN">ERN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ETB">ETB</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="EUR">EUR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="FJD">FJD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="FKP">FKP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GBP">GBP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GEL">GEL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GGP">GGP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GHS">GHS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GIP">GIP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GMD">GMD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GNF">GNF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GTQ">GTQ</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="GYD">GYD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="HKD">HKD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="HNL">HNL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="HRK">HRK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="HTG">HTG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="HUF">HUF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="IDR">IDR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ILS">ILS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="IMP">IMP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="INR">INR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="IQD">IQD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="IRR">IRR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ISK">ISK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="JEP">JEP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="JMD">JMD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="JOD">JOD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="JPY">JPY</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KES">KES</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KGS">KGS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KHR">KHR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KMF">KMF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KPW">KPW</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KRW">KRW</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KWD">KWD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KYD">KYD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="KZT">KZT</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LAK">LAK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LBP">LBP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LKR">LKR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LRD">LRD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LSL">LSL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="LYD">LYD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MAD">MAD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MDL">MDL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MGA">MGA</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MKD">MKD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MMK">MMK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MNT">MNT</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MOP">MOP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MRO">MRO</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MRU">MRU</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MUR">MUR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MVR">MVR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MWK">MWK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MXN">MXN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MYR">MYR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="MZN">MZN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NAD">NAD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NGN">NGN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NIO">NIO</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NOK">NOK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NPR">NPR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="NZD">NZD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="OMR">OMR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PAB">PAB</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PEN">PEN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PGK">PGK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PHP">PHP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PKR">PKR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PLN">PLN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="PYG">PYG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="QAR">QAR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="RON">RON</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="RSD">RSD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="RUB">RUB</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="RWF">RWF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SAR">SAR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SBD">SBD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SCR">SCR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SDG">SDG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SEK">SEK</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SGD">SGD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SHP">SHP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SLL">SLL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SOS">SOS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SRD">SRD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SSP">SSP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="STD">STD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="STN">STN</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SVC">SVC</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SYP">SYP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="SZL">SZL</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="THB">THB</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TJS">TJS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TMT">TMT</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TND">TND</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TOP">TOP</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TRY">TRY</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TTD">TTD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TWD">TWD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="TZS">TZS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="UAH">UAH</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="UGX">UGX</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="USD">USD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="UYU">UYU</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="UZS">UZS</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="VEF">VEF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="VND">VND</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="VUV">VUV</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="WST">WST</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XAF">XAF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XAG">XAG</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XAU">XAU</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XCD">XCD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XDR">XDR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XOF">XOF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XPD">XPD</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XPF">XPF</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="XPT">XPT</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="YER">YER</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ZAR">ZAR</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ZMW">ZMW</a></li>
        <li><a class="currencyOption" onClick='window.changeCurrency(this)' id="ZWL">ZWL</a></li>
    </ul>
</span>

